#### General/shared rules ####
tmpdir: /scratch.global/zhoux379/temp
email: zhoux379@umn.edu
java:
    mem: 8G
    tmpdir: /scratch.global/zhoux379/temp
threads: 1    
dirl: logs
dirp: pbs
dird: data

db:
    ref: /home/springer/zhoux379/data/genome/B73/10_genome.fna
    chrom_sizes: /home/springer/zhoux379/data/genome/B73/15_intervals/01.chrom.sizes
    regions: /home/springer/zhoux379/data/genome/B73/15_intervals/20.gap.sep.60win.tsv
    #regions: /home/springer/zhoux379/data/genome/B73/17_regions/11.chrom.10win.tsv

annotation:
    gtf: /home/springer/zhoux379/data/genome/B73/51.gtf
    bed: /home/springer/zhoux379/data/genome/B73/v37/gene.bed

zip_re: (\.gz|\.zip|\.bz2)

fq_rename:
    idir: 09_raw_fastq
    odir: 10_fastq

fastq_dump:
    odir: 10_fastq_slow
fasterq_dump:
    odir: 10_fastq
    threads: 4
    mem: 10GB

deinterleave:
    idir: 09_raw_fastq
    odir: 10_fastq
    extra: ''

trimmomatic:
    idir: 10_fastq
    odir: 14_trim
    adapter_pe: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-PE.fa 
    adapter_se: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-SE.fa 
    threads: 8

bbduk:
    idir: 10_fastq
    odir: 14_trim
    cmd: bbduk.sh
    refs:
        - /home/springer/zhoux379/source/bbmap/resources/polyA.fa.gz
        - /home/springer/zhoux379/source/bbmap/resources/truseq.fa.gz
    extra: k=13 ktrim=r useshortkmers=t mink=5 qtrim=r trimq=10 minlength=20

fastqc:
    idir: 14_trim
    extra: ''

bwa:
    idir: 14_trim
    odir1: 21_bwa
    odir2: 22_bam
    index: /home/springer/zhoux379/data/genome/B73/21_dbs/bwa/db
    threads: 12
    extra: ''

star:
    idir: 14_trim
    odir1: 21_star
    odir2: 22_bam
    #index: /home/springer/zhoux379/data/genome/B73/21_star
    index: /home/springer/zhoux379/data/genome/B73/21_dbs/star
    extra: "--outSAMmapqUnique 60
        --outFilterType BySJout 
        --outFilterMultimapNmax 20 
        --alignSJoverhangMin 8 
        --alignSJDBoverhangMin 1 
        --outFilterMismatchNmax 999 
        --outFilterMismatchNoverReadLmax 1.0 
        --alignIntronMin 20 
        --alignIntronMax 1000000 
        --alignMatesGapMax 1000000 
        --outSAMunmapped Within KeepPairs"
    threads: 8

hisat2:
    idir: 14_trim
    odir1: 21_hisat2
    odir2: 22_bam
    index: /home/springer/zhoux379/data/genome/B73/21_hisat2/maize
    extra: --new-summary
    threads: 8

sambamba:
    threads: 8
    sort:
        extra: -m 11GB
    merge:
        extra: ''
    flagstat:
        extra: ''

featurecounts:
    idir: 22_bam
    odir: 31_featurecounts
    out: featurecounts.tsv
    cmd: featureCounts
    #gtf: /home/springer/zhoux379/data/genome/B73/51.gtf
    gtf: /home/springer/zhoux379/data/genome/B73/50_annotation/10.gtf
    extra: --primary -Q 20 -t exon -g gene_id --byReadGroup
    threads: 4

callvnt:
    idir: 22_bam
    odir1: 25_gvcf
    odir2: 26_vcf_by_region
    outfile: 26.vcf.gz

bcftools:
    #ref: /home/springer/zhoux379/data/genome/B73/11_genome.fas
    ref: /home/springer/zhoux379/data/genome/B73/10_genome.fna
    call:
        threads: 1
        extra: ''
    merge:
        threads: 2
        extra: ''
    concat:
        threads: 1
        extra: ''
    gtcheck:
        odir: 27_gtcheck
        vcf: /home/springer/zhoux379/projects/biomap/data/variants/62biomAP.snp.vcf.gz
        extra: -G 1

gatk:
    cmd: gatk
    java_mem: 20G
    #ref: /home/springer/zhoux379/data/genome/B73/21_gatk/maize.fasta
    #ref.fai: /home/springer/zhoux379/data/genome/B73/21.gatk/maize.fasta.fai
    #ref.dict: /home/springer/zhoux379/data/genome/B73/21.gatk/maize.dict
    ref: /home/springer/zhoux379/data/genome/B73/21_dbs/gatk/db.fasta
    ref.fai: /home/springer/zhoux379/data/genome/B73/21_dbs/gatk/db.fasta.fai
    ref.dict: /home/springer/zhoux379/data/genome/B73/21_dbs/gatk/db.dict
    haplotype_caller:
        java_mem: 14G
        threads: 1
        extra: ''
    gather_vcfs:
        threads: 1
        extra: ''
    genotype_gvcfs:
        java_mem: 20G
        threads: 4
        extra: ''
    variant_filtration:
        threads: 1
        extra: ''

ase:
    idir: 22_bam
    odir: 33_ase
    variant_dir: /home/springer/zhoux379/projects/biomap/data/variants_reseq
    variant_dir2: /home/springer/zhoux379/projects/biomap/data/variants_rnaseq
    extra: ''

multiqc:
    extra: ''

wgc:
    genomes:
        B73:
            assembly: /home/springer/zhoux379/data/genome/B73/10_genome.fna
            annotation: /home/springer/zhoux379/data/genome/B73/50_annotation/10.gtb
            chroms: B01 B02 B03 B04 B05 B06 B07 B08 B09 B10 B99
        Mo17:
            assembly: /home/springer/zhoux379/data/genome/Mo17/10_genome.fna
            annotation: /home/springer/zhoux379/data/genome/Mo17/51.gtb
            #chroms: M01 M02 M03 M04 M05 M06 M07 M08 M09 M10 M99
        W22:
            assembly: /home/springer/zhoux379/data/genome/W22/10_genome.fna
            annotation: /home/springer/zhoux379/data/genome/W22/51.gtb
            #chroms: W01 W02 W03 W04 W05 W06 W07 W08 W09 W10 W99
        PH207:
            assembly: /home/springer/zhoux379/data/genome/PH207/10_genome.fna
            annotation: /home/springer/zhoux379/data/genome/PH207/51.gtb
            #chroms: P01 P02 P03 P04 P05 P06 P07 P08 P09 P10 P99
    dirg: 01_genomes
    dira: 11_align
    dirc: 12_merged
    npieces: 30
    prepare:
        threads: 1
        extra: ''
    align:
        threads: 4
        extra: ''
    merge:
        threads: 1
        extra: ''
    chain:
        threads: 1
        extra: ''

