#### General/shared rules ####
tmpdir: /scratch.global/zhoux379/temp
email: zhoux379@umn.edu
java:
    mem: 8G
    tmpdir: /scratch.global/zhoux379/temp
threads: 1    
dirl: logs
dirp: pbs
dirq: qc

db:
    ref: /home/springer/zhoux379/data/genome/B73/11_genome.fas
    chrom_sizes: /home/springer/zhoux379/data/genome/B73/15.sizes

annotation:
    gtf: /home/springer/zhoux379/data/genome/B73/51.gtf
    bed: /home/springer/zhoux379/data/genome/B73/v37/gene.bed

zip_re: (\.gz|\.zip|\.bz2)

deinterleave:
    idir: 09_raw_fastq
    odir: 10_fastq
    extra: ''

trimmomatic:
    idir: 10_fastq
    odir: 14_trim
    adapter_pe: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-PE.fa 
    adapter_se: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-SE.fa 
    threads: 8

bbduk:
    idir: 10_fastq
    odir: 14_trim
    cmd: bbduk.sh
    refs:
        - /home/springer/zhoux379/source/bbmap/resources/polyA.fa.gz
        - /home/springer/zhoux379/source/bbmap/resources/truseq.fa.gz
    extra: k=13 ktrim=r useshortkmers=t mink=5 qtrim=r trimq=10 minlength=20

fastqc:
    idir: 14_trim
    extra: ''

star:
    idir: 14_trim
    odir:
        - 21_star
        - 22_bam
    index: /home/springer/zhoux379/data/genome/B73/21_star
    extra: --outFilterType BySJout 
        --outFilterMultimapNmax 20 
        --alignSJoverhangMin 8 
        --alignSJDBoverhangMin 1 
        --outFilterMismatchNmax 999 
        --outFilterMismatchNoverReadLmax 1.0 
        --alignIntronMin 20 
        --alignIntronMax 1000000 
        --alignMatesGapMax 1000000 
        --outSAMunmapped Within KeepPairs 
    threads: 8

hisat2:
    idir: 14_trim
    odir:
        - 21_hisat2
        - 22_bam
    index: /home/springer/zhoux379/data/genome/B73/21_hisat2/maize
    extra: --new-summary
    threads: 8

sambamba:
    threads: 8
    sort:
        extra: ''
    merge:
        extra: ''

featurecounts:
    idir: 22_bam
    outfile: 31_featurecounts/01.txt
    cmd: featureCounts
    gtf: /home/springer/zhoux379/data/genome/B73/51.gtf
    extra: --primary -Q 20 -t exon -g gene_id --byReadGroup
    threads: 8

bcftools:
    ref: /home/maize/shared/databases/genomes/Zea_mays/B73/Zea_mays.AGPv4.dna.toplevel.fa
    regions: 1 2 3 4 5 6 7 8 9 10
    call:
        idir: 22_bam
        odir: 25_called
        extra: ''
    concat:
        idir: 25_called
        outfile: 25.bcf
        extra: ''

ase:
    idir: 22_bam
    odir: 33-ase
    variant_dir: /home/springer/zhoux379/projects/biomap/data/variants_reseq
    variant_dir2: /home/springer/zhoux379/projects/biomap/data/variants_rnaseq
    extra: ''

multiqc:
    extra: ''

gatk:
    idir: 22_bam
    odir: 26_gatk
    outfile: 26.vcf.gz
    cmd: gatk3
    java_mem: 20G
    ref: /home/springer/zhoux379/data/genome/B73/21_gatk/maize.fasta
    ref.fai: /home/springer/zhoux379/data/genome/B73/21.gatk/maize.fasta.fai
    ref.dict: /home/springer/zhoux379/data/genome/B73/21.gatk/maize.dict
    haplotype_caller:
        threads: 4
        extra: ''
    genotype_gvcfs:
        java_mem: 10G
        threads: 4
        extra: ''
    variant_filtration:
        threads: 1
        extra: ''
