#### General/shared rules ####
tmpdir: /scratch.global/zhoux379/temp
email: zhoux379@umn.edu
java:
    mem: 8G
    tmpdir: /scratch.global/zhoux379/temp
threads: 1    
dirl: logs
dirp: pbs
dirq: qc

db:
    ref: /home/springer/zhoux379/data/genome/B73/11_genome.fas
    chrom_sizes: /home/springer/zhoux379/data/genome/B73/15.sizes

annotation:
    gtf: /home/springer/zhoux379/data/genome/B73/51.gtf
    bed: /home/springer/zhoux379/data/genome/B73/v37/gene.bed

zip_re: (\.gz|\.zip|\.bz2)

trimmomatic:
    idir: 10.fastq
    odir: 14.trim
    adapter_pe: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-PE.fa 
    adapter_se: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-SE.fa 
    threads: 8

bbduk:
    idir: 10.fastq
    odir: 14.trim
    cmd: bbduk.sh
    refs:
        - /home/springer/zhoux379/source/bbmap/resources/polyA.fa.gz
        - /home/springer/zhoux379/source/bbmap/resources/truseq.fa.gz
    extra: k=13 ktrim=r useshortkmers=t mink=5 qtrim=r trimq=10 minlength=20

fastqc:
    idir: 14.trim
    extra: ''

star:
    idir: 14.trim
    odir:
        - 21.bam.raw
        - 22.bam
    index: /home/springer/zhoux379/data/genome/B73/21.star
    extra: --outFilterType BySJout 
        --outFilterMultimapNmax 20 
        --alignSJoverhangMin 8 
        --alignSJDBoverhangMin 1 
        --outFilterMismatchNmax 999 
        --outFilterMismatchNoverReadLmax 1.0 
        --alignIntronMin 20 
        --alignIntronMax 1000000 
        --alignMatesGapMax 1000000 
        --outSAMunmapped Within KeepPairs 
    threads: 8

hisat2:
    idir: 14.trim
    odir:
        - 21.bam.raw
        - 22.bam
    index: /home/springer/zhoux379/data/genome/B73/21.hisat2/maize
    extra: --new-summary
    threads: 8

sambamba:
    threads: 8
    sort:
        extra: ''
    merge:
        extra: ''

featurecounts:
    idir: 22.bam
    odir: 24.featurecounts
    cmd: featureCounts
    gtf: /home/springer/zhoux379/data/genome/B73/51.gtf
    extra: --primary -Q 20 -t exon -g gene_id --byReadGroup
    threads: 8

bcftools_call:
    extra: ''

ase:
    idir: 22.bam
    odir: 26.ase
    variant_dir: /home/springer/zhoux379/projects/biomap/data/variants_reseq
    variant_dir2: /home/springer/zhoux379/projects/biomap/data/variants
    extra: ''

multiqc:
    extra: ''

gatk:
    idir: 22.bam
    odir: 25.gatk
    cmd: gatk
    java_mem: 20G
    ref: /home/springer/zhoux379/data/genome/B73/21.gatk/maize.fasta
    ref.fai: /home/springer/zhoux379/data/genome/B73/21.gatk/maize.fasta.fai
    ref.dict: /home/springer/zhoux379/data/genome/B73/21.gatk/maize.dict
    haplotype_caller:
        mode: HaplotypeCaller
        threads: 1
        extra: ''
    variant_filtration:
        mode: VariantFiltration
        threads: 1
        extra: ''
