__default__:
  q: 0
  nodes: 1
  ppn: 1
  runtime: 8
  mem: 8
  aruntime: 1
  amem: 5
  aq: 0
  load: 1
  M: zhoux379@umn.edu
  m: a
  r: n
  N: s.{rule}.{wildcards}
  o: jobs/{rule}/{wildcards}.out
  e: jobs/{rule}/{wildcards}.err

