__default__:
  q: small
  nodes: 1
  ppn: 1
  runtime: 8
  mem: 8
  aruntime: 8
  amem: 8
  M: zhoux379@umn.edu
  m: a
  r: n
  N: s.{rule}.{wildcards}
  o: pbs/{rule}/{wildcards}.out 
  e: pbs/{rule}/{wildcards}.err

