__default__:
  q: small
  nodes: 1
  ppn: 1
  walltime: 8:00:00
  mem: 8GB
  M: zhoux379@umn.edu
  m: a
  r: n
  N: s.{rule}.{wildcards}
  o: pbs/{rule}/{wildcards}.out 
  e: pbs/{rule}/{wildcards}.err

