#cluster: "pbs-submit.py --depend \"{dependencies}\""
cluster: "pbs-submit.py"
cluster-config: "snk/clusters/base.yaml"
cluster-status: "pbs-status.py"
jobscript: "pbs-jobscript.sh"
jobs: 10
immediate-submit: False
verbose: False
#verbose: True
notemp: True
