#### General/shared rules ####
tmpdir: /scratch.global/zhoux379/temp
dir_project: /home/springer/zhoux379/projects
dir_cache: /scratch.global/zhoux379
wid: data
oid: raw
dirl: logs
dirj: jobs
email: zhoux379@umn.edu
java:
  mem: 8
  tmpdir: /scratch.global/zhoux379/temp
zip_re: (\.gz|\.zip|\.bz2)
valid:
  source:
    - sra
    - local
  format:
    - umgc
    - sra
    - jgi
    - simple
  readtype:
    - illumina
    - solid
    - 3rnaseq
  stranded:
    - 'yes'
    - 'no'
    - 'reverse'
  mapper:
    - star
    - hisat2
    - bwa
    - bismark
config: /home/springer/zhoux379/projects/master.xlsx
config_job_default: /home/springer/zhoux379/git/snk/clusters/base.yml
job_default:
  id: job0
  group: g0
  idir: ''
  odir: ''
  nodes: 1
  q: amdsmall
  ppn: 1
  runtime: 8
  mem: 8
  appn: 0
  aruntime: 1
  amem: 5
  load: 0
  tasks: ''
  qs: 'amdsmall'
  ppns: ''
  mems: ''
  rates: ''
  M: zhoux379@umn.edu
  m: a
  r: n
  N: smk
  o: smk.o
  e: smk.e
pbs_queue_config:
  amdsmall:
    ppn: 128
    mem: 250
    runtime: 96
  amdslarge:
    ppn: 128
    mem: 250
    runtime: 24
  amd2tb:
    ppn: 128
    mem: 2000
    runtime: 96
  v100:
    ppn: 24
    mem: 375
    runtime: 24
dirg: /home/springer/zhoux379/projects/genome/data
db:
  outkeys:
    fasta: ref chrom_size chrom_bed gap fchain bchain
    annotation: gff gff_db gtf tsv bed des fna faa
                lgff lgff_db lgtf ltsv lbed ldes lfna lfaa
    tandup: xout
    rds: xout
    bowtie2: xout
    bwa: xout
    bismark: xout
    star: xout
    hisat2: xout
    salmon: xout
    lastn: xout
    lastp: xout
    blastn: xout
    blastp: xout
    blat: x.2bit x.ooc
    gatk: xref xref.dict
    snpeff: xcfg
  fasta:
    xdir: .
    ref: 10_genome.fna
    chrom_size: 15_intervals/01.chrom.sizes
    chrom_bed: 15_intervals/01.chrom.bed
    gap: 15_intervals/11.gap.bed
    fchain: 08_seq_map/mapf.chain
    bchain: 08_seq_map/mapb.chain
    win11: 15_intervals/20.win11.tsv
    win56: 15_intervals/20.win56.tsv
    win127: 15_intervals/20.win127.tsv
  annotation:
    xdir: 50_annotation
    gff: 10.gff
    gff_db: 10.gff.db
    gtf: 10.gtf
    tsv: 10.tsv
    bed: 10.bed
    des: 10.desc.tsv
    fna: 10.fna
    faa: 10.faa
    lgff: 15.gff
    lgff_db: 15.gff.db
    lgtf: 15.gtf
    ltsv: 15.tsv
    lbed: 15.bed
    ldes: 15.desc.tsv
    lfna: 15.fna
    lfaa: 15.faa
    bsseq: 35.intervals.bed
  tandup:
    xdir: 52_tandup
    xout: 05.tandup.pro.tsv
  rds:
    xdir: .
    xout: 55.rds
  blat:
    xdir: 21_dbs/blat
    xpre: db
    x.2bit: db.2bit
    x.ooc: db.2bit.tile11.ooc
  bwa:
    xdir: 21_dbs/bwa
    xpre: db
    xout: db.bwt
  bowtie2:
    xdir: 21_dbs/bowtie2
    xpre: ''
  star:
    xdir: 21_dbs/star
    xpre: ''
    xout: SA
  gatk:
    xdir: 21_dbs/gatk
    xref: db.fasta
    xref.fai: db.fasta.fai
    xref.dict: db.dict
    known_sites: known_sites.vcf.gz
  hisat2:
    xdir: 21_dbs/hisat2
    xpre: db
    xout: db.1.ht2
  salmon:
    xdir: 21_dbs/salmon
    xpre: db
    xout: db/complete_ref_lens.bin
  snpeff:
    xdir: 21_dbs/snpeff
    xcfg: snpEff.config
    xout: snpEffectPredictor.bin
  lastn:
    xdir: 21_dbs/lastn
    xpre: db
    xout: db.prj
  lastp:
    xdir: 21_dbs/lastp
    xpre: db
    xout: db.prj
  blastn:
    xdir: 21_dbs/blastn
    xpre: db
    xout: db.nsq
  blastp:
    xdir: 21_dbs/blastp
    xpre: db
    xout: db.psq
  bismark:
    xdir: 21_dbs/bismark
    xpre: ''
    xout: Bisulfite_Genome/CT_conversion/BS_CT.rev.2.bt2
barn:
  home: /home/springer/zhoux379/projects/barn/data
  idir_local: 06_local_list
  idir_sra: 09_sra_list
  od09z: 09_fq_compress
  od09v: 09_fq_deinterleave
  od09d: 09_fq_dump
  od09s: 09_fq_dump_slow
  fqdir: fastq
  od15: 15_fastqc
  odir: 15_read_list
trimming:
  idir: /scratch.global/zhoux379/barn/data/fastq
  part_size: 100000000
  od12: 12_parts
  od14p: 14_fastp
  od14t: 14_trimmomatic
  od14b: 14_bbduk
  odir: 15_trim
  out: trimming.tsv
trimmomatic:
  adapter_pe: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-PE.fa
  adapter_se: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-SE.fa
bbduk:
  cmd: bbduk.sh
  refs:
      - /home/springer/zhoux379/source/bbmap/resources/polyA.fa.gz
      - /home/springer/zhoux379/source/bbmap/resources/truseq.fa.gz
  extra: k=13 ktrim=r useshortkmers=t mink=5 qtrim=r trimq=10 minlength=20
mapping:
  idir: 15_trim
  od21b: 21_bwa
  od21s: 21_star
  od21h: 21_hisat2
  od21m: 21_bismark
  odir: 22_bam
merge_bamstats:
  out: bamstats.tsv
  outv: bamstats_v.tsv
rnaseq:
  idir: 22_bam
  ase_bcf: /home/springer/zhoux379/projects/reseq/data/ase_bcf
  od31f: 31_featurecounts
  od31m: 31_mmquant
  od33a: 33a_ase1
  od33b: 33b_ase2
  od33c: 33c_ase3
  od33d: 33d_ase4
  od33e: 33e_ase5
  od41: 41_gt
  of42: 42_merged.vcf.gz
  od43: 43_snpbinner
  meta: meta.tsv
  out_fcnt: featurecounts.rds
  out_mmq: mmquant.rds
  out_cpm: cpm.rds
  out_ase: ase.rds
  out_ase2: ase2.rds
  out_ril: ril.rds
cleanbam:
  idir: 22_bam
  od23: 23_mark_dup
  od24a: 24_bcftools/01_by_region
  of24b: 24_bcftools/02.vcf.gz
  of24c: 24_bcftools/03.hq.vcf.gz
  od24: 24_base_recal
bsseq:
  idir: 23_mark_dup
  od31: 31_bismark
  od33: 33_bsm_extract
  odir: bed
callvnt:
  truth_sites_snp: /home/springer/zhoux379/projects/reseq/data/20_hmp/21.snp.sites.vcf.gz
  truth_sites_idl: /home/springer/zhoux379/projects/reseq/data/21_biomap/05.idl.sites.vcf.gz
  idir: 24_base_recal
  od25: 25_gvcf_by_region
  od26: 26_gvcf
  odir: gvcf
  out: vcfstats.tsv
  out_idl: vcfstats_idl.tsv
callvnt2:
  vdir: gvcf
  idir: 11_geno_list
  od05: 05_combine_gvcfs
  od10: 10_genomics_db
  od20: 20_vcfs_by_region
  of30: 30.vcf.gz
  od31: 31_picked
  of31a: 31.snp.vcf.gz
  of31b: 31.idl.vcf.gz
  of32a: 32.recal.vcf
  of32b: 32.tranches
  of33: 33.snp.vcf.gz
  of34a: 34.recal.vcf
  of34b: 34.tranches
  of35: 35.snp.indel.vcf.gz
  od37: 37_filtered
  od38: 38_snpeff
  od39: 39_stats
  odir: vcf
  out_stat: bcftools_stats.rds
callvnt3:
  od10: 10_filtered
  of11: 11.vcf.gz
  of11b: 11.stat.tsv
  od21: 21_vcf
  od22: 22_bcf
gatk:
  cmd: gatk
wgc:
  od10: 10_genomes
  od20: 20_align
  od23: 23_merged
  od41: 41_blastn
  od42: 42_blastp
  od43: 43_lastn
  od44: 44_lastp
  od50: 50_orthofinder
  of50: output/Orthogroups/Orthogroups.tsv
  od55: 55_synteny
  rf10: 10.vnt.bed
  rf15: 15.B73.tsv
  rf20q: 20.q.ortholog.tsv
  rf20t: 20.t.ortholog.tsv
  npieces: 30
# statistics & reports


