#### General/shared rules ####
tmpdir: /scratch.global/zhoux379/temp
email: zhoux379@umn.edu
java:
    mem: 8
    tmpdir: /scratch.global/zhoux379/temp
dirl: logs
dirp: pbs
dird: data
zip_re: (\.gz|\.zip|\.bz2)

### genomes
dirg: /home/springer/zhoux379/data/genome
B73:
    gdir: B73
Mo17:
    gdir: Mo17
W22:
    gdir: W22
PH207:
    gdir: PH207
PHB47:
    gdir: PHB47

### software
fq_compress:
    id: fqGz
    idir: 09_fastq_raw
    odir: 10_fastq
    ppn: 6
    runtime: 5
    mem: 30
    aruntime: 10
    amem: 5

fastq_dump:
    id: fqDump
    odir: 10_fastq_slow
    jdir: fq_dump
    ppn: 1
    runtime: 20
    mem: 20
    aruntime: 10
    amem: 5
fasterq_dump:
    id: fqDump
    odir: 10_fastq
    ppn: 4
    runtime: 10
    mem: 11
    aruntime: 10
    amem: 5

deinterleave:
    id: fqDiv
    idir: 09_fq_interleaved
    odir: 10_fastq
    extra: ''
    ppn: 10
    runtime: 10
    mem: 20
    aruntime: 10
    amem: 5

fastqc:
    id: fqc
    idir: 14_trim
    extra: ''
    ppn: 1
    runtime: 5
    mem: 10
    aruntime: 10
    amem: 5

trimmomatic:
    id: trimm
    idir: 10_fastq
    odir: 14_trim
    adapter_pe: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-PE.fa 
    adapter_se: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-SE.fa 
    ppn: 8
    runtime: 12
    mem: 10
    aruntime: 10
    amem: 5

bbduk:
    id: bbduk
    idir: 10_fastq
    odir: 14_trim
    cmd: bbduk.sh
    refs:
        - /home/springer/zhoux379/source/bbmap/resources/polyA.fa.gz
        - /home/springer/zhoux379/source/bbmap/resources/truseq.fa.gz
    extra: k=13 ktrim=r useshortkmers=t mink=5 qtrim=r trimq=10 minlength=20
    ppn: 1
    runtime: 12
    mem: 10
    aruntime: 10
    amem: 5

blat:
    id: blat
    xdir: blat
    xpre: db
    x.2bit: db.2bit
    x.ooc: db.2bit.tile11.ooc
    runtime: 12
    mem: 10
    aruntime: 10
    amem: 5

bowtie2:
    id: bowti
    xdir: bowtie2
    ppn: 4
    runtime: 20
    mem: 20
    aruntime: 10
    amem: 5

bwa:
    id: bwa
    xdir: bwa
    xpre: db
    xout: db.bwt
    idir: 14_trim
    odir1: 21_bwa
    odir2: 22_bam
    extra: ''
    ppn: 12
    runtime: 20
    mem: 30
    aruntime: 20
    amem: 10

star:
    id: star
    xdir: star
    xpre: '' 
    xout: SA
    idir: 14_trim
    odir1: 21_star
    odir2: 22_bam
    extra: "--outSAMmapqUnique 60
        --outFilterType BySJout 
        --outFilterMultimapNmax 20 
        --alignSJoverhangMin 8 
        --alignSJDBoverhangMin 1 
        --outFilterMismatchNmax 999 
        --outFilterMismatchNoverReadLmax 1.0 
        --alignIntronMin 20 
        --alignIntronMax 1000000 
        --alignMatesGapMax 1000000 
        --outSAMunmapped Within KeepPairs"
    ppn: 8
    runtime: 15
    mem: 20
    aruntime: 15
    amem: 10

hisat2:
    id: hisat
    xdir: hisat2
    xpre: db
    xout: db.1.ht2
    idir: 14_trim
    odir1: 21_hisat2
    odir2: 22_bam
    extra: --new-summary
    ppn: 8
    runtime: 15
    mem: 20
    aruntime: 15
    amem: 10

sambamba:
    ppn: 8
    runtime: 8
    mem: 12
    aruntime: 10
    amem: 12
    sort:
        id: sbbS
        extra: -m 11GB
    merge:
        id: sbbM
        extra: ''
    flagstat:
        id: sbbF
        extra: ''
        runtime: 4

featurecounts:
    id: featuecnts
    idir: 22_bam
    odir: 31_featurecounts
    extra: --primary -Q 20 -t exon -g gene_id --byReadGroup
    ppn: 4
    runtime: 5
    mem: 15
    aruntime: 10
    amem: 10

cleanbam:
    id: cleanBam
    idir: 22_bam
    odir1: 23_mark_dup
    odir2: 24_base_recal

callvnt:
    id: callvnt
    idir: 24_base_recal
    odir1: 25_gvcf
    odir2: 26_vcf_by_region
    outfile: 26.vcf.gz

bcftools:
    call:
        id: bcfCa
        ppn: 1
        runtime: 60
        mem: 50
    merge:
        id: bcfM
        ppn: 2
        runtime: 23
        mem: 20
    concat:
        id: bcfCo
        ppn: 1
        runtime: 10
        mem: 15
    gtcheck:
        id: bcfGt
        odir: 27_gtcheck
        vcf: /home/springer/zhoux379/projects/biomap/data/variants/62biomAP.snp.vcf.gz
        extra: -G 1
        ppn: 1
        runtime: 1
        mem: 5

gatk:
    xdir: gatk
    xref: db.fasta
    xref.fai: db.fasta.fai
    xref.dict: db.dict
    known_sites: known_sites.vcf.gz
    cmd: gatk
    mark_duplicates:
        id: markD
        picard: True
        ppn: 1
        runtime: 20
        mem: 15
        aruntime: 20
        amem: 5
    base_recalibrator:
        id: baseR
        ppn: 1
        runtime: 20
        mem: 15
        aruntime: 10
        amem: 5
    apply_bqsr:
        id: applB
        ppn: 1
        runtime: 20
        mem: 20
        aruntime: 20
        amem: 5
    haplotype_caller:
        id: haplC
        ppn: 1
        runtime: 30
        mem: 15
        aruntime: 20
        amem: 5
    gather_vcfs:
        id: gathV
        picard: True
        ppn: 1
        runtime: 5
        mem: 10
        aruntime: 5
        amem: 5
    combine_gvcfs:
        id: combG
        ppn: 1
        runtime: 20
        mem: 30
        aruntime: 20
        amem: 5
    genotype_gvcfs:
        id: genoG
        ppn: 1
        runtime: 30
        mem: 30
        aruntime: 20
        amem: 5
    variant_filtration:
        id: variF
        ppn: 1
        runtime: 5
        mem: 20
        aruntime: 5
        amem: 5

ase:
    id: ase
    idir: 22_bam
    odir: 33_ase
    gene_bed: /home/springer/zhoux379/data/genome/B73/50_annotation/10.ase.bed
    vdir: /home/springer/zhoux379/projects/biomap/data/variants/ase29
    vdir2: /home/springer/zhoux379/projects/biomap/data/variants/ase35
    ppn: 1
    runtime: 20
    mem: 20
    aruntime: 20
    amem: 10

bam_stat:
    id: bamst 
    ppn: 1
    runtime: 8
    mem: 4
    aruntime: 8
    amem: 4

merge_featurecounts:
    id: merge_feat
    idir: 31_featurecounts
    out: featurecounts.tsv

merge_bamstats:
    id: merge_bamst
    #idir: 22_bam
    out: bamstats.tsv

merge_ase:
    id: merge_ase
    idir: 33_ase
    out: ase.tsv

multiqc:
    id: multiqc
    out: multiqc.html
    ppn: 1
    runtime: 10
    mem: 15
    aruntime: 10
    amem: 10

