#### General/shared rules ####
tmpdir: /scratch.global/zhoux379/temp
email: zhoux379@umn.edu
java:
    mem: 8G
    tmpdir: /scratch.global/zhoux379/temp
threads: 1    
dirl: logs
dirp: pbs
dird: data
zip_re: (\.gz|\.zip|\.bz2)
dirg: /home/springer/zhoux379/data/genome

genomes:
    B73:
        gdir: B73
    Mo17:
        gdir: Mo17
    W22:
        gdir: W22
    PH207:
        gdir: PH207
    PHB47:
        gdir: PHB47

fq_compress:
    idir: 09_fastq_raw
    odir: 10_fastq
    ppn: 6
    walltime: 5:00:00
    mem: 30GB

fastq_dump:
    odir: 10_fastq_slow
fasterq_dump:
    odir: 10_fastq
    ppn: 4
    walltime: 10:00:00
    mem: 11GB

deinterleave:
    idir: 09_fq_interleaved
    odir: 10_fastq
    extra: ''
    ppn: 10
    walltime: 10:00:00
    mem: 20GB

fastqc:
    idir: 14_trim
    extra: ''
    ppn: 1
    walltime: 5:00:00
    mem: 10GB

trimmomatic:
    idir: 10_fastq
    odir: 14_trim
    adapter_pe: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-PE.fa 
    adapter_se: /home/springer/zhoux379/software/miniconda3/share/trimmomatic/adapters/TruSeq3-SE.fa 
    ppn: 8
    walltime: 12:00:00
    mem: 10GB

bbduk:
    idir: 10_fastq
    odir: 14_trim
    cmd: bbduk.sh
    refs:
        - /home/springer/zhoux379/source/bbmap/resources/polyA.fa.gz
        - /home/springer/zhoux379/source/bbmap/resources/truseq.fa.gz
    extra: k=13 ktrim=r useshortkmers=t mink=5 qtrim=r trimq=10 minlength=20
    ppn: 1
    walltime: 12:00:00
    mem: 10GB

blat:
    xdir: blat
    xpre: db
    x.2bit: db.2bit
    x.ooc: db.2bit.tile11.ooc
    mem: 10GB

bowtie2:
    xdir: bowtie2

bwa:
    xdir: bwa
    xpre: db
    xout: db.bwt
    idir: 14_trim
    odir1: 21_bwa
    odir2: 22_bam
    extra: ''
    ppn: 12
    walltime: 30:00:00
    mem: 40GB

star:
    xdir: star
    xpre: '' 
    xout: SA
    xthreads: 4
    idir: 14_trim
    odir1: 21_star
    odir2: 22_bam
    extra: "--outSAMmapqUnique 60
        --outFilterType BySJout 
        --outFilterMultimapNmax 20 
        --alignSJoverhangMin 8 
        --alignSJDBoverhangMin 1 
        --outFilterMismatchNmax 999 
        --outFilterMismatchNoverReadLmax 1.0 
        --alignIntronMin 20 
        --alignIntronMax 1000000 
        --alignMatesGapMax 1000000 
        --outSAMunmapped Within KeepPairs"
    ppn: 8
    walltime: 10:00:00
    mem: 35GB

hisat2:
    xdir: hisat2
    xpre: db
    xout: db.1.ht2
    xthreads: 4
    idir: 14_trim
    odir1: 21_hisat2
    odir2: 22_bam
    extra: --new-summary
    ppn: 8
    walltime: 10:00:00
    mem: 20GB

sambamba:
    ppn: 8
    walltime: 8:00:00
    mem: 12GB
    sort:
        extra: -m 11GB
    merge:
        extra: ''
    flagstat:
        extra: ''
        walltime: 4:00:00

featurecounts:
    idir: 22_bam
    odir: 31_featurecounts
    out: featurecounts.tsv
    cmd: featureCounts
    extra: --primary -Q 20 -t exon -g gene_id --byReadGroup
    ppn: 4
    walltime: 5:00:00
    mem: 15GB

callvnt:
    idir: 22_bam
    odir1: 25_gvcf
    odir2: 26_vcf_by_region
    outfile: 26.vcf.gz

bcftools:
    ppn: 1
    call:
        ppn: 1
        walltime: 60:00:00
        mem: 50GB
    merge:
        ppn: 2
        walltime: 23:00:00
        mem: 20GB
    concat:
        ppn: 1
        walltime: 10:00:00
        mem: 15GB
    gtcheck:
        odir: 27_gtcheck
        vcf: /home/springer/zhoux379/projects/biomap/data/variants/62biomAP.snp.vcf.gz
        extra: -G 1
        ppn: 1
        walltime: 1:00:00
        mem: 5GB

gatk:
    xdir: gatk
    xref: db.fasta
    xref.fai: db.fasta.fai
    xref.dict: db.dict
    cmd: gatk
    java_mem: 20G
    haplotype_caller:
        java_mem: 14G
        ppn: 1
        walltime: 15:00:00
        mem: 15GB
    gather_vcfs:
        ppn: 1
        walltime: 5:00:00
        mem: 10GB
    genotype_gvcfs:
        java_mem: 20G
        ppn: 4
        walltime: 50:00:00
        mem: 40GB
    variant_filtration:
        ppn: 1
        walltime: 5:00:00
        mem: 20GB

ase:
    idir: 22_bam
    odir: 33_ase
    variant_dir: /home/springer/zhoux379/projects/biomap/data/variants_reseq
    variant_dir2: /home/springer/zhoux379/projects/biomap/data/variants_rnaseq

multiqc:
    ppn: 1
    walltime: 10:00:00
    mem: 20GB

