config_default: /home/springer/zhoux379/git/snk/configs/base.yml
pid: briggs
studylist: /home/springer/zhoux379/projects/maize.expression/data/01.cfg.tsv
study: me99b
ase:
  vdir: /home/springer/zhoux379/projects/briggs/data/variants
  vdir2: /home/springer/zhoux379/projects/briggs/data/variants

