config_default: /home/springer/zhoux379/git/snk/configs/base.yml
dirw: /home/springer/zhoux379/projects/polyTE/data/flank_mapping
cfg: 01.cfg.tsv
species: maize
fm:
  idir: 05_gff
  odir1: 11_loc
  odir2: 12_seq
  odir3: 14_bwa
  odir4: 15_coord
  bwa:
    id: bwa
    ppn: 8
    runtime: 10
    mem: 20
    aruntime: 10
    amem: 1
  coord:
    id: coord
    ppn: 1
    runtime: 2
    mem: 20
    aruntime: 1
    amem: 1
lastz:
  id: lz
  idir: 31_te_windows
  odir: 32_lastz
  ppn: 1
  runtime: 60
  mem: 20
  aruntime: 10
  amem: 1
