config_default: /home/springer/zhoux379/git/snk/configs/base.yaml
dirw: /home/springer/zhoux379/projects/polyTE/data/flank_mapping
cfg: 01.cfg.tsv
species: maize
fm:
    idir: 05_gff
    odir1: 11_loc
    odir2: 12_seq
    odir3: 14_bwa
    odir4: 15_coord
    bwa:
        ppn: 8
        walltime: 10:00:00
        mem: 20GB
lastz:
    idir: 31_te_windows
    odir: 32_lastz
    ppn: 1
    walltime: 60:00:00
    mem: 20GB
