config_default: /home/springer/zhoux379/git/snk/configs/base.yaml
dirw: /home/springer/zhoux379/data/genome
genomes:
    B73:
        prefix: B
        gap: 10000
        dbs: fasta blat bwa star gatk hisat2
    Mo17:
        prefix: M
        gap: 10000
        dbs: fasta blat bwa star gatk hisat2
    W22:
        prefix: W
        gap: 10000
        dbs: fasta blat bwa star gatk
    PH207:
        prefix: P
        gap: 5000
        dbs: fasta blat bwa star gatk
    PHB47:
        prefix: PHB47_
        gap: 10000
        dbs: fasta blat bwa #star gatk
#fasta:
