config_default: /home/springer/zhoux379/git/snk/configs/base.yml
pid: genome
ddir: 21_dbs
adir: 50_annotation
# index databases
fasta:
  id: fa
  ppn: 1
  runtime: 2
  mem: 20
blat_index:
  id: blatIdx
  ppn: 1
  runtime: 1
  mem: 20
gatk_index:
  id: gatkIdx
  ppn: 1
  runtime: 1
  mem: 10
blast_index:
  id: blastIdx
  ppn: 1
  runtime: 2
  mem: 20
bwa_index:
  id: bwaIdx
  ppn: 1
  runtime: 10
  mem: 20
  amem: 0
  aruntime: 0
star_index:
  id: starIdx
  ppn: 4
  runtime: 10
  mem: 60
  amem: 0
  aruntime: 0
hisat2_index:
  id: hst2Idx
  q: 1
  ppn: 4
  runtime: 5
  mem: 150
  amem: 0
  aruntime: 0
snpeff_index:
  id: snpfIdx
  ppn: 1
  runtime: 5
  mem: 30
  amem: 0
  aruntime: 0
bismark_index:
  id: bsmIdx
  ppn: 6
  runtime: 20
  mem: 30
  amem: 0
  aruntime: 0
# gff db
anno1_clean:
  out: 10.gff
  id: 1cln
  ppn: 1
  runtime: 1
  mem: 10
anno2_index:
  id: 2idx
  ppn: 1
  runtime: 3
  mem: 15
  aruntime: 1
  amem: 5
anno3_blast:
  id: 3bla
  ppn: 8
  runtime: 10
  mem: 25
  aruntime: 10
  amem: 5
anno4_tandup:
  id: 4dup
  ppn: 1
  runtime: 2
  mem: 25
  aruntime: 1
  amem: 1
prepR:
  id: prepR
  ppn: 1
  runtime: 2
  mem: 15
