config_default: /home/springer/zhoux379/git/snk/configs/base.yaml
dirw: /home/springer/zhoux379/data/genome
genomes: B73 Mo17 W22 PH207 PHB47
B73:
    prefix: B
    gap: 10000
    dbs: fasta blat bwa star gatk hisat2
Mo17:
    prefix: M
    gap: 10000
    dbs: fasta blat bwa star gatk hisat2
W22:
    prefix: W
    gap: 10000
    dbs: fasta blat bwa star gatk
PH207:
    prefix: P
    gap: 5000
    dbs: fasta blat bwa star gatk
PHB47:
    prefix: PHB47_
    gap: 10000
    dbs: fasta blat bwa star gatk

#fasta:
bwa_index:
    ppn: 1
    runtime: 10
    mem: 20

star_index:
    ppn: 4
    runtime: 10
    mem: 60

hisat2_index:
    q: ram256g
    ppn: 4
    runtime: 5
    mem: 150
