config_default: /home/springer/zhoux379/git/snk/configs/base.yml
dirw: /home/springer/zhoux379/projects/grn/data
grn:
  cfg: 10.dataset.xlsx
  ppn: 1
  runtime: 2
  mem: 20
  aruntime: 2
  amem: 10
  evtype: tf go br bm
  get_exp_mat:
    id: em
    odir: 11_exp_mat
    ppn: 1
    runtime: 1
    mem: 30
    aruntime: 1
    amem: 10
  genie3:
    id: genie3
    tf: '09.tf.txt'
    odir: 12_genie3
    ppn: 12
    runtime: 30 # n18a needs >= 70h run time
    mem: 50
    aruntime: 20
    amem: 1
  pkl2rda:
    id: pkl2rda
    ppn: 1
    runtime: 1
    mem: 50
    aruntime: 1
    amem: 10
  eval:
    id: eval
    odir: 13_eval
    ppn: 1
    runtime: 4
    mem: 30
  eval_merge:
    id: evm
    odir: 14_eval_sum
    ppn: 1
    runtime: 5
    mem: 30
