config_default: /home/springer/zhoux379/git/snk/configs/base.yaml
dirw: /home/springer/zhoux379/projects/grn/data
grn:
  cfg: 10.dataset.xlsx
  ppn: 1
  runtime: 2
  mem: 20
  aruntime: 2
  amem: 10
  evtype: tf go br bm
  genie3:
    id: genie3
    idir: 11_input
    odir: 12_output
    ppn: 12
    runtime: 30
    mem: 25
    aruntime: 10
    amem: 5
  pkl2rda:
    id: pkl2rda
    idir: 12_output
    odir: 12_output
    ppn: 1
    runtime: 1
    mem: 30
    aruntime: 1
    amem: 10
  eval:
    id: eval
    idir: 12_output
    odir: 13_eval
    ppn: 1
  eval_merge:
    id: evm
    idir: 13_eval
    odir: 14_eval_sum
    ppn: 1
    runtime: 5
    mem: 30
