config_default: /home/springer/zhoux379/git/snk/configs/base.yaml
dirw: /home/springer/zhoux379/projects/maize.grn/data
genie3:
    cfg: 10.dataset.tsv
    idir: 11_input_fpkm
    odir: 12_output_fpkm
    #q: ram256g
    ppn: 12
    walltime: 50:00:00
    mem: 30GB
