config_default: /home/springer/zhoux379/git/snk/configs/base.yml
pid: grn
grn:
  cfg: 10.dataset.xlsx
  tf: 09.tf.txt
  evtype: tf go br bm
  od11: 11_em_raw
  od12: 12_em_filt
  od14: 14_grn
  od15: 15_grn_eval
  od17: 17_eval
  od18: 18_eval_sum
  get_exp_mat:
    id: em
    ppn: 1
    runtime: 1
    mem: 30
    aruntime: 1
    amem: 10
  make_grn:
    id: grn
    ppn: 12
    runtime: 30 # n18a needs >= 70h run time
    mem: 30
    aruntime: 30
    amem: 1
  pkl2rds:
    id: pkl2rds
    ppn: 1
    runtime: 4
    mem: 20
    aruntime: 4
    amem: 10
  eval_model:
    id: evg
    ppn: 8
    runtime: 30
    mem: 30
    aruntime: 10
    amem: 5
  merge_eval_model:
    id: evmg
    ppn: 1
    runtime: 5
    mem: 30
    aruntime: 5
    amem: 1
  eval:
    id: eval
    ppn: 1
    runtime: 4
    mem: 30
  eval_merge:
    id: evm
    ppn: 1
    runtime: 5
    mem: 30
