config_default: /home/springer/zhoux379/git/snk/configs/base.yml
pid: grn
grn:
  cfg: 10.dataset.xlsx
  tf: 09.tf.txt
  gopts:
    - rf
    - et
    - xgb
  eopts:
    - tf
    - go
    - br
    - bm
  od11: 11_em_raw
  od12: 12_em_filt
  od14: 14_grn_pkl
  od15: 15_grn_rds
  od17: 17_eval
  od18: 18_eval_sum
