config_default: /home/springer/zhoux379/git/snk/configs/base.yaml
dir_project: /home/springer/zhoux379/projects/reseq
dir_cache: /scratch.global/zhoux379/reseq
studylist: /home/springer/zhoux379/projects/reseq/data/01.cfg.xlsx
dirw: /home/springer/zhoux379/projects/reseq/data/20_hmp
hmp:
  refo: /home/springer/zhoux379/data/genome/B73/download/raw.fna
  refn: /home/springer/zhoux379/data/genome/B73/21_dbs/gatk/db.fasta
  chain3: /home/springer/zhoux379/data/genome/B73/chain/AGPv3_to_AGPv4.chain.gz
  chain4: /home/springer/zhoux379/data/genome/B73/08_seq_map/mapf.chain
  ppn: 1
  runtime: 5
  mem: 20
  aruntime: 5
  amem: 10
  liftover:
    id: lif
    idir: 01_raw
    odir: 04_liftover
    ppn: 1
    runtime: 10
    mem: 30
    aruntime: 5
    amem: 10
  merge:
    id: mg
    out: 10.vcf.gz
    ppn: 1
    runtime: 5
    mem: 20
    aruntime: 5
    amem: 10

