config_default: /home/springer/zhoux379/git/snk/configs/base.yml
pid: reseq
wid: data
y:
  j01:
    yid: j01
    n: 436
    ref: Zmays_B73
    run: False
  j07:
    yid: j07
    n: 962
    ref: Zmays_B73
    run: False
  j08:
    yid: j08
    n: 119
    ref: Zmays_B73
    run: True


