config_default: /home/springer/zhoux379/git/snk/configs/base.yaml
dir_project: /home/springer/zhoux379/projects/rnaseq
dir_cache: /scratch.global/zhoux379/rnaseq
studylist: /home/springer/zhoux379/projects/rnaseq/data/01.cfg.xlsx
