config_default: /home/springer/zhoux379/git/snk/configs/base.yaml
dir_project: /home/springer/zhoux379/projects/wgc
dir_cache: /scratch.global/zhoux379/wgc
genomes: B73 Mo17 W22 PH207 PHB47
B73:
    assembly: /home/springer/zhoux379/data/genome/B73/10_genome.fna
    annotation: /home/springer/zhoux379/data/genome/B73/50_annotation/10.gtb
    chroms: B01 B02 B03 B04 B05 B06 B07 B08 B09 B10 B99
Mo17:
    assembly: /home/springer/zhoux379/data/genome/Mo17/10_genome.fna
    annotation: /home/springer/zhoux379/data/genome/Mo17/51.gtb
    #chroms: M01 M02 M03 M04 M05 M06 M07 M08 M09 M10 M99
W22:
    assembly: /home/springer/zhoux379/data/genome/W22/10_genome.fna
    annotation: /home/springer/zhoux379/data/genome/W22/51.gtb
    #chroms: W01 W02 W03 W04 W05 W06 W07 W08 W09 W10 W99
PH207:
    assembly: /home/springer/zhoux379/data/genome/PH207/10_genome.fna
    annotation: /home/springer/zhoux379/data/genome/PH207/51.gtb
    #chroms: P01 P02 P03 P04 P05 P06 P07 P08 P09 P10 P99
wgc:
    dir1: 10_genomes
    dir2: 20_align
    dir3: 30_merged
    npieces: 30
    prepare:
        id: prep
        ppn: 1
        runtime: 10
        mem: 10
        aruntime: 10
        amem: 5
    align:
        id: aln
        ppn: 4
        runtime: 20
        mem: 20
        aruntime: 20
        amem: 10
    merge:
        id: merge
        ppn: 1
        runtime: 1
        mem: 20
        aruntime: 2
        amem: 5 
    chain:
        id: chain
        ppn: 1
        runtime: 20
        mem: 20
        aruntime: 20
        amem: 10
comps:
    - Mo17-B73
    - W22-B73
