genomes:
    B73:
        assembly: /home/springer/zhoux379/data/genome/B73/10_genome.fna
        annotation: /home/springer/zhoux379/data/genome/B73/50_annotation/10.gtb
        chroms: B01 B02 B03 B04 B05 B06 B07 B08 B09 B10 B99
    Mo17:
        assembly: /home/springer/zhoux379/data/genome/Mo17/10_genome.fna
        annotation: /home/springer/zhoux379/data/genome/Mo17/51.gtb
        #chroms: M01 M02 M03 M04 M05 M06 M07 M08 M09 M10 M99
    W22:
        assembly: /home/springer/zhoux379/data/genome/W22/10_genome.fna
        annotation: /home/springer/zhoux379/data/genome/W22/51.gtb
        #chroms: W01 W02 W03 W04 W05 W06 W07 W08 W09 W10 W99
    PH207:
        assembly: /home/springer/zhoux379/data/genome/PH207/10_genome.fna
        annotation: /home/springer/zhoux379/data/genome/PH207/51.gtb
        #chroms: P01 P02 P03 P04 P05 P06 P07 P08 P09 P10 P99
dirg: 01_genomes
dira: 11_align
dirc: 12_merged
npieces: 30
prepare:
    ppn: 1
    walltime: 10:00:00
    mem: 10GB
align:
    ppn: 4
    walltime: 20:00:00
    mem: 20GB
merge:
    ppn: 1
    walltime: 1:00:00
    mem: 20GB
chain:
    ppn: 1
    walltime: 40:00:00
    mem: 20GB

